### ISSUE TITLE
New Feature: Option Greeks

### ISSUE THREAD

**Issue by DidierRLopes** [rleonard21/PyTradier#15]
Hey,

We at Gamestonk Terminal were wondering if your project allowed to get the greeks from the option-chain?

https://documentation.tradier.com/brokerage-api/markets/get-options-chains

**Comment by rleonard21** [comment]
Hi,

It looks like the options-chain greek features were released after I wrote the options portion of PyTradier. Adding this feature shouldn't be too difficult, since the new fields just need to be added to `options.py` (https://github.com/rleonard21/PyTradier/blob/master/pytradier/securities/option.py).

 I'm a bit busy for the next few weeks, but it'd be greatly appreciated if anyone is willing to contribute this change to PyTradier!

**Comment by Pedler7** [comment]
I believe it's just a flag when calling the option chains in the API, I'll try and look at it later this week/weekend.

**Comment by DidierRLopes** [comment]
Nice, thanks for the reply.

@Pedler7 just beat me to it. Exactly, I believe it's a `'greeks': 'true'` in the `params` request.

Thanks @Pedler7, that's perfect. I can also have a look at it myself if you're busy. Just let me know!

**Comment by rleonard21** [comment]
@Pedler7 implemented this feature in #16

**Comment by DidierRLopes** [comment]
Thanks for this!!
